[package]
name = "usbtest"
version = "0.1.0"
authors = ["Laszlo Ashin <laszlo@ashin.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
